Fp 80 close chat
SupportAI-Project/SupportAI-Frontend pull request #29
Opened 2024-08-28 15:11 UTC by roiy0987

2024-08-28 15:36 UTC, JosephOri requested changes

2024-08-28 15:36 UTC, JosephOri commented on src/common/utils/index.ts
this should be in the same directory as theme.ts

2024-08-28 15:36 UTC, JosephOri commented on src/app/(admin)/new_dashboard/components/SupportMessageList/index.tsx
> +        {messages &&
the condition `messages` doesn't check if message array is empty

![Screenshot 2024-08-28 183232](https://github.com/user-attachments/assets/48b22497-46b5-456d-aee7-652784c3eb59)

2024-08-28 19:18 UTC, nitzanto requested changes

2024-08-28 19:18 UTC, nitzanto commented on src/api/base.client.ts
> +    return this.request<T>(endpoint, "PATCH", body, options);
Why was this changed from PUT to PATCH. This will affect a lot of API calls that are using PUT. There's no need to make that change currently

2024-08-28 19:18 UTC, nitzanto commented on src/app/(admin)/new_dashboard/components/ChatHeader/hooks/useGuide.ts
> +  }
Why not use tanstack query for this? Also we want to display some sort of error message to the user if there was an error.

2024-08-28 19:18 UTC, nitzanto commented on src/app/(admin)/new_dashboard/components/ChatHeader/index.tsx
> +
We can use tanstack query. Then you can get the loading state from it.

2024-08-28 19:18 UTC, nitzanto commented on src/app/(user)/new_chat/[userId]/components/UserMessageList/index.tsx
> +                  );
use conditional rendering

2024-08-28 19:18 UTC, nitzanto commented on src/common/components/Message/index.tsx
> +import { use } from "react";
remove this import

2024-08-28 20:58 UTC, roiy0987 commented on src/api/base.client.ts
> +    return this.request<T>(endpoint, "PATCH", body, options);
the backend is based "PATCH" and not "PUT"
![image](https://github.com/user-attachments/assets/422171f5-8a17-467c-a0e0-efdfc8387071)
![image](https://github.com/user-attachments/assets/a0d69d1b-a147-44dd-9e84-6ad60fd56814)

and so on....

2024-08-29 07:20 UTC, roiy0987 commented on src/app/(admin)/new_dashboard/components/SupportMessageList/index.tsx
> +        {messages &&
what's the problem with that ?

2024-08-29 16:39 UTC, JosephOri commented on src/app/(admin)/new_dashboard/components/SupportMessageList/index.tsx
> +        {messages &&
an empty array as a condition returns true, therefore there isnt a checking over there about the case where the array is empty

2024-08-31 21:17 UTC, nitzanto approved these changes

2024-08-31 21:19 UTC, JosephOri approved these changes

2024-08-31 21:19 UTC, merged